### ISSUE TITLE
Username uniqueness not guaranteed

### ISSUE THREAD

**Issue by epsilontheta** [Lommix/WichtelBotTheSequel#1]
There seems to be an issue with the handling of duplicate usernames: after the following line

https://github.com/Lommix/WichtelBotTheSequel/blob/88c47be0905d0497b034f667372a1e39dba1000b/server/register.go#L69

There should be a return statement or?
Sorry, not that fluent in golang.
I just noticed duplicate usernames in the sqlite db.

Thanks for your project, been running it in Docker for christmas 🎄 .

**Comment by Lommix** [comment]
You are right, I just had the same issue with my family this Christmas and forced them to change names. You are, probably the first one, to use this old side project of mine =).

Do you want to make your third pull request?
